# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)
student1 = seed Student, {username: 'husseny', name: 'Husseny', email: 'husseny@web.de'}, {password: '12341234', password_confirmation: '12341234'}
student2 = seed Student, {username: 'student', name: 'student', email: 'student@web.de'}, {password: '12341234', password_confirmation: '12341234'}
seed Developer, {username: 'marco', name: 'Marco', email: 'marco@web.de'}, {password: '12341234', password_confirmation: '12341234'}
seed Admin, {username: 'administrator', name: 'Admin', email: 'admin@web.de'}, {password: '12341234', password_confirmation: '12341234'}

seed Course, {title: 'Mathematics', description: 'This is a course to teach Maths to grades 1 and 2 using the common core standards.'}
seed Course, {title: 'English', description: 'This is an English course that is taught using the common core standards.'}

seed Domain, {title: 'Operations & Algebric Thinking', screening_title: 'Think like a Calculator', description: 'A long description here', course: Course.first}
seed Domain, {title: 'Numbers & Operations in Base Ten', screening_title: 'Numbers Madness', description: 'A long description here', course: Course.first}
seed Domain, {title: 'Measurement and Data', screening_title: 'The Millimeter Difference', description: 'A long description here', course: Course.first}
seed Domain, {title: 'Geometry', screening_title: 'Shapes', description: 'A long description here', course: Course.first}
seed Domain, {title: 'Numbers & Operations - Fractions', screening_title: 'Numbers Madness 2', description: 'A long description here', course: Course.first}

skill1 = seed Skill, {description: 'Use addition and subtraction within 20 to solve word problems involving situations of adding to, taking from, putting together, taking apart, and comparing, with unknowns in all positions, e.g., by using objects, drawings, and equations with a symbol for the unknown number to represent the problem.', grade: 1, domain: Domain.first, course: Course.first}, {title: 'CCSS.Math.Content.1.OA.A.1'}
skill2 = seed Skill, {description: 'Solve word problems that call for addition of three whole numbers whose sum is less than or equal to 20, e.g., by using objects, drawings, and equations with a symbol for the unknown number to represent the problem.', grade: 1, domain: Domain.first, course: Course.first}, {title: 'CCSS.Math.Content.1.OA.A.2'}
seed Skill, {description: 'Apply properties of operations as strategies to add and subtract.2 Examples: If 8 + 3 = 11 is known, then 3 + 8 = 11 is also known. (Commutative property of addition.) To add 2 + 6 + 4, the second two numbers can be added to make a ten, so 2 + 6 + 4 = 2 + 10 = 12. (Associative property of addition.)', grade: 1, domain: Domain.first, course: Course.first}, {title: 'CCSS.Math.Content.1.OA.B.3'}
seed Skill, {description: 'Understand subtraction as an unknown-addend problem. For example, subtract 10 - 8 by finding the number that makes 10 when added to 8.', grade: 1, domain: Domain.first, course: Course.first}, {title: 'CCSS.Math.Content.1.OA.B.4'}
seed Skill, {description: 'Relate counting to addition and subtraction (e.g., by counting on 2 to add 2).', grade: 1, domain: Domain.first, course: Course.first}, {title: 'CCSS.Math.Content.1.OA.C.5'}
seed Skill, {description: 'Add and subtract within 20, demonstrating fluency for addition and subtraction within 10. Use strategies such as counting on; making ten (e.g., 8 + 6 = 8 + 2 + 4 = 10 + 4 = 14); decomposing a number leading to a ten (e.g., 13 - 4 = 13 - 3 - 1 = 10 - 1 = 9); using the relationship between addition and subtraction (e.g., knowing that 8 + 4 = 12, one knows 12 - 8 = 4); and creating equivalent but easier or known sums (e.g., adding 6 + 7 by creating the known equivalent 6 + 6 + 1 = 12 + 1 = 13).', grade: 1, domain: Domain.first, course: Course.first}, {title: 'CCSS.Math.Content.1.OA.C.6'}
seed Skill, {description: 'Understand the meaning of the equal sign, and determine if equations involving addition and subtraction are true or false. For example, which of the following equations are true and which are false? 6 = 6, 7 = 8 - 1, 5 + 2 = 2 + 5, 4 + 1 = 5 + 2.', grade: 1, domain: Domain.first, course: Course.first}, {title: 'CCSS.Math.Content.1.OA.D.7'}
seed Skill, {description: 'Determine the unknown whole number in an addition or subtraction equation relating three whole numbers. For example, determine the unknown number that makes the equation true in each of the equations 8 + ? = 11, 5 = _ - 3, 6 + 6 = _.', grade: 1, domain: Domain.first, course: Course.first}, {title: 'CCSS.Math.Content.1.OA.D.8'}
seed Skill, {description: 'Count to 120, starting at any number less than 120. In this range, read and write numerals and represent a number of objects with a written numeral.', grade: 1, domain: Domain.second, course: Course.first}, {title: 'CCSS.Math.Content.1.NBT.A.1'}
seed Skill, {description: 'Understand that the two digits of a two-digit number represent amounts of tens and ones. Understand the following as special cases: A) 10 can be thought of as a bundle of ten ones — called a "ten." B)The numbers from 11 to 19 are composed of a ten and one, two, three, four, five, six, seven, eight, or nine ones. C) The numbers 10, 20, 30, 40, 50, 60, 70, 80, 90 refer to one, two, three, four, five, six, seven, eight, or nine tens (and 0 ones).', grade: 1, domain: Domain.second, course: Course.first}, {title: 'CCSS.Math.Content.1.NBT.B.2'}
seed Skill, {description: 'Compare two two-digit numbers based on meanings of the tens and ones digits, recording the results of comparisons with the symbols >, =, and <.', grade: 1, domain: Domain.second, course: Course.first}, {title: 'CCSS.Math.Content.1.NBT.B.3'}
seed Skill, {description: 'Add within 100, including adding a two-digit number and a one-digit number, and adding a two-digit number and a multiple of 10, using concrete models or drawings and strategies based on place value, properties of operations, and/or the relationship between addition and subtraction; relate the strategy to a written method and explain the reasoning used. Understand that in adding two-digit numbers, one adds tens and tens, ones and ones; and sometimes it is necessary to compose a ten.', grade: 1, domain: Domain.second, course: Course.first}, {title: 'CCSS.Math.Content.1.NBT.C.4'}
seed Skill, {description: 'Given a two-digit number, mentally find 10 more or 10 less than the number, without having to count; explain the reasoning used.', grade: 1, domain: Domain.second, course: Course.first}, {title: 'CCSS.Math.Content.1.NBT.C.5'}
seed Skill, {description: 'Subtract multiples of 10 in the range 10-90 from multiples of 10 in the range 10-90 (positive or zero differences), using concrete models or drawings and strategies based on place value, properties of operations, and/or the relationship between addition and subtraction; relate the strategy to a written method and explain the reasoning used.', grade: 1, domain: Domain.second, course: Course.first}, {title: 'CCSS.Math.Content.1.NBT.C.6'}
seed Skill, {description: 'Order three objects by length; compare the lengths of two objects indirectly by using a third object.', grade: 1, domain: Domain.third, course: Course.first}, {title: 'CCSS.Math.Content.1.MD.A.1'}
seed Skill, {description: 'Express the length of an object as a whole number of length units, by laying multiple copies of a shorter object (the length unit) end to end; understand that the length measurement of an object is the number of same-size length units that span it with no gaps or overlaps. Limit to contexts where the object being measured is spanned by a whole number of length units with no gaps or overlaps.', grade: 1, domain: Domain.third, course: Course.first}, {title: 'CCSS.Math.Content.1.MD.A.2'}
seed Skill, {description: 'Tell and write time in hours and half-hours using analog and digital clocks.', grade: 1, domain: Domain.third, course: Course.first}, {title: 'CCSS.Math.Content.1.MD.B.3'}
seed Skill, {description: 'Organize, represent, and interpret data with up to three categories; ask and answer questions about the total number of data points, how many in each category, and how many more or less are in one category than in another.', grade: 1, domain: Domain.third, course: Course.first}, {title: 'CCSS.Math.Content.1.MD.C.4'}
seed Skill, {description: 'Distinguish between defining attributes (e.g., triangles are closed and three-sided) versus non-defining attributes (e.g., color, orientation, overall size); build and draw shapes to possess defining attributes.', grade: 1, domain: Domain.fourth, course: Course.first}, {title: 'CCSS.Math.Content.1.G.A.1'}
seed Skill, {description: 'Compose two-dimensional shapes (rectangles, squares, trapezoids, triangles, half-circles, and quarter-circles) or three-dimensional shapes (cubes, right rectangular prisms, right circular cones, and right circular cylinders) to create a composite shape, and compose new shapes from the composite shape.Students should apply the principle of transitivity of measurement to make indrirect comparisons, but they need not use this technical term', grade: 1, domain: Domain.fourth, course: Course.first}, {title: 'CCSS.Math.Content.1.G.A.2'}
seed Skill, {description: 'Partition circles and rectangles into two and four equal shares, describe the shares using the words halves, fourths, and quarters, and use the phrases half of, fourth of, and quarter of. Describe the whole as two of, or four of the shares. Understand for these examples that decomposing into more equal shares creates smaller shares.', grade: 1, domain: Domain.fourth, course: Course.first}, {title: 'CCSS.Math.Content.1.G.A.3'}

seed Skill, {description: 'Use addition and subtraction within 100 to solve one- and two-step word problems involving situations of adding to, taking from, putting together, taking apart, and comparing, with unknowns in all positions, e.g., by using drawings and equations with a symbol for the unknown number to represent the problem.', grade: 2, domain: Domain.first, course: Course.first}, {title: 'CCSS.Math.Content.2.OA.A.1'}
seed Skill, {description: 'Fluently add and subtract within 20 using mental strategies.By the end, know from memory all sums of two one-digit numbers.', grade: 2, domain: Domain.first, course: Course.first}, {title: 'CCSS.Math.Content.2.OA.B.2'}
seed Skill, {description: 'Determine whether a group of objects (up to 20) has an odd or even number of members, e.g., by pairing objects or counting them by 2s; write an equation to express an even number as a sum of two equal addends.', grade: 2, domain: Domain.first, course: Course.first}, {title: 'CCSS.Math.Content.2.OA.C.3'}
seed Skill, {description: 'Use addition to find the total number of objects arranged in rectangular arrays with up to 5 rows and up to 5 columns; write an equation to express the total as a sum of equal addends.', grade: 2, domain: Domain.first, course: Course.first}, {title: 'CCSS.Math.Content.2.OA.C.4'}
seed Skill, {description: 'Understand that the three digits of a three-digit number represent amounts of hundreds, tens, and ones; e.g., 706 equals 7 hundreds, 0 tens, and 6 ones. Understand the following as special cases: A) 100 can be thought of as a bundle of ten tens — called a "hundred." B) The numbers 100, 200, 300, 400, 500, 600, 700, 800, 900 refer to one, two, three, four, five, six, seven, eight, or nine hundreds (and 0 tens and 0 ones).', grade: 2, domain: Domain.second, course: Course.first}, {title: 'CCSS.Math.Content.2.NBT.A.1'}
seed Skill, {description: 'Count within 1000; skip-count by 5s, 10s, and 100s.', grade: 2, domain: Domain.second, course: Course.first}, {title: 'CCSS.Math.Content.2.NBT.A.2'}
seed Skill, {description: 'Read and write numbers to 1000 using base-ten numerals, number names, and expanded form.', grade: 2, domain: Domain.second, course: Course.first}, {title: 'CCSS.Math.Content.2.NBT.A.3'}
seed Skill, {description: 'Compare two three-digit numbers based on meanings of the hundreds, tens, and ones digits, using >, =, and < symbols to record the results of comparisons.', grade: 2, domain: Domain.second, course: Course.first}, {title: 'CCSS.Math.Content.2.NBT.A.4'}
seed Skill, {description: 'Fluently add and subtract within 100 using strategies based on place value, properties of operations, and/or the relationship between addition and subtraction.', grade: 2, domain: Domain.second, course: Course.first}, {title: 'CCSS.Math.Content.2.NBT.B.5'}
seed Skill, {description: 'Add up to four two-digit numbers using strategies based on place value and properties of operations.', grade: 2, domain: Domain.second, course: Course.first}, {title: 'CCSS.Math.Content.2.NBT.B.6'}
seed Skill, {description: 'Add and subtract within 1000, using concrete models or drawings and strategies based on place value, properties of operations, and/or the relationship between addition and subtraction; relate the strategy to a written method. Understand that in adding or subtracting three-digit numbers, one adds or subtracts hundreds and hundreds, tens and tens, ones and ones; and sometimes it is necessary to compose or decompose tens or hundreds.', grade: 2, domain: Domain.second, course: Course.first}, {title: 'CCSS.Math.Content.2.NBT.B.7'}
seed Skill, {description: 'Mentally add 10 or 100 to a given number 100-900, and mentally subtract 10 or 100 from a given number 100-900.', grade: 2, domain: Domain.second, course: Course.first}, {title: 'CCSS.Math.Content.2.NBT.B.8'}
seed Skill, {description: 'Explain why addition and subtraction strategies work, using place value and the properties of operations.', grade: 2, domain: Domain.second, course: Course.first}, {title: 'CCSS.Math.Content.2.NBT.B.9'}
seed Skill, {description: 'Measure the length of an object by selecting and using appropriate tools such as rulers, yardsticks, meter sticks, and measuring tapes.', grade: 2, domain: Domain.third, course: Course.first}, {title: 'CCSS.Math.Content.2.MD.A.1'}
seed Skill, {description: 'Measure the length of an object twice, using length units of different lengths for the two measurements; describe how the two measurements relate to the size of the unit chosen.', grade: 2, domain: Domain.third, course: Course.first}, {title: 'CCSS.Math.Content.2.MD.A.2'}
seed Skill, {description: 'Estimate lengths using units of inches, feet, centimeters, and meters.', grade: 2, domain: Domain.third, course: Course.first}, {title: 'CCSS.Math.Content.2.MD.A.3'}
seed Skill, {description: 'Measure to determine how much longer one object is than another, expressing the length difference in terms of a standard length unit.', grade: 2, domain: Domain.third, course: Course.first}, {title: 'CCSS.Math.Content.2.MD.A.4'}
seed Skill, {description: 'Use addition and subtraction within 100 to solve word problems involving lengths that are given in the same units, e.g., by using drawings (such as drawings of rulers) and equations with a symbol for the unknown number to represent the problem.', grade: 2, domain: Domain.third, course: Course.first}, {title: 'CCSS.Math.Content.2.MD.B.5'}
seed Skill, {description: 'Represent whole numbers as lengths from 0 on a number line diagram with equally spaced points corresponding to the numbers 0, 1, 2, ..., and represent whole-number sums and differences within 100 on a number line diagram.', grade: 2, domain: Domain.third, course: Course.first}, {title: 'CCSS.Math.Content.2.MD.B.6'}
seed Skill, {description: 'Tell and write time from analog and digital clocks to the nearest five minutes, using a.m. and p.m', grade: 2, domain: Domain.third, course: Course.first}, {title: 'CCSS.Math.Content.2.MD.C.7'}
seed Skill, {description: 'Solve word problems involving dollar bills, quarters, dimes, nickels, and pennies, using $ and ¢ symbols appropriately. Example: If you have 2 dimes and 3 pennies, how many cents do you have?', grade: 2, domain: Domain.third, course: Course.first}, {title: 'CCSS.Math.Content.2.MD.C.8'}
seed Skill, {description: 'Generate measurement data by measuring lengths of several objects to the nearest whole unit, or by making repeated measurements of the same object. Show the measurements by making a line plot, where the horizontal scale is marked off in whole-number units.', grade: 2, domain: Domain.third, course: Course.first}, {title: 'CCSS.Math.Content.2.MD.D.9'}
seed Skill, {description: 'Draw a picture graph and a bar graph (with single-unit scale) to represent a data set with up to four categories. Solve simple put-together, take-apart, and compare problems1 using information presented in a bar graph.', grade: 2, domain: Domain.third, course: Course.first}, {title: 'CCSS.Math.Content.2.MD.D.10'}
seed Skill, {description: 'Recognize and draw shapes having specified attributes, such as a given number of angles or a given number of equal faces. Identify triangles, quadrilaterals, pentagons, hexagons, and cubes. Sizes are compared directly or visually, not compared by measuring.', grade: 2, domain: Domain.fourth, course: Course.first}, {title: 'CCSS.Math.Content.2.G.A.1'}
seed Skill, {description: 'Partition a rectangle into rows and columns of same-size squares and count to find the total number of them.', grade: 2, domain: Domain.fourth, course: Course.first}, {title: 'CCSS.Math.Content.2.G.A.2'}
seed Skill, {description: 'Partition circles and rectangles into two, three, or four equal shares, describe the shares using the words halves, thirds, half of, a third of, etc., and describe the whole as two halves, three thirds, four fourths. Recognize that equal shares of identical wholes need not have the same shape.', grade: 2, domain: Domain.fourth, course: Course.first}, {title: 'CCSS.Math.Content.2.G.A.3'}

seed Skill, {title: 'CCSS.MATH.CONTENT.3.OA.A.1', description: 'Interpret products of whole numbers, e.g., interpret 5 × 7 as the total number of objects in 5 groups of 7 objects each. For example, describe a context in which a total number of objects can be expressed as 5 × 7.', grade: 3, domain: Domain.first, course: Course.first}
seed Skill, {title: 'CCSS.MATH.CONTENT.3.OA.A.2', description: 'Interpret whole-number quotients of whole numbers, e.g., interpret 56 ÷ 8 as the number of objects in each share when 56 objects are partitioned equally into 8 shares, or as a number of shares when 56 objects are partitioned into equal shares of 8 objects each. For example, describe a context in which a number of shares or a number of groups can be expressed as 56 ÷ 8.', grade: 3, domain: Domain.first, course: Course.first}
seed Skill, {title: 'CCSS.MATH.CONTENT.3.OA.A.3', description: 'Use multiplication and division within 100 to solve word problems in situations involving equal groups, arrays, and measurement quantities, e.g., by using drawings and equations with a symbol for the unknown number to represent the problem.', grade: 3, domain: Domain.first, course: Course.first}
seed Skill, {title: 'CCSS.MATH.CONTENT.3.OA.A.4', description: 'Determine the unknown whole number in a multiplication or division equation relating three whole numbers. For example, determine the unknown number that makes the equation true in each of the equations 8 × ? = 48, 5 = _ ÷ 3, 6 × 6 = ?', grade: 3, domain: Domain.first, course: Course.first}
seed Skill, {title: 'CCSS.MATH.CONTENT.3.OA.B.5', description: 'Apply properties of operations as strategies to multiply and divide.2 Examples: If 6 × 4 = 24 is known, then 4 × 6 = 24 is also known. (Commutative property of multiplication.) 3 × 5 × 2 can be found by 3 × 5 = 15, then 15 × 2 = 30, or by 5 × 2 = 10, then 3 × 10 = 30. (Associative property of multiplication.) Knowing that 8 × 5 = 40 and 8 × 2 = 16, one can find 8 × 7 as 8 × (5 + 2) = (8 × 5) + (8 × 2) = 40 + 16 = 56. (Distributive property.)', grade: 3, domain: Domain.first, course: Course.first}
seed Skill, {title: 'CCSS.MATH.CONTENT.3.OA.B.6', description: 'Understand division as an unknown-factor problem. For example, find 32 ÷ 8 by finding the number that makes 32 when multiplied by 8.', grade: 3, domain: Domain.first, course: Course.first}
seed Skill, {title: 'CCSS.MATH.CONTENT.3.OA.C.7', description: 'Fluently multiply and divide within 100, using strategies such as the relationship between multiplication and division (e.g., knowing that 8 × 5 = 40, one knows 40 ÷ 5 = 8) or properties of operations. By the end of Grade 3, know from memory all products of two one-digit numbers.', grade: 3, domain: Domain.first, course: Course.first}
seed Skill, {title: 'CCSS.MATH.CONTENT.3.OA.D.8', description: 'Solve two-step word problems using the four operations. Represent these problems using equations with a letter standing for the unknown quantity. Assess the reasonableness of answers using mental computation and estimation strategies including rounding.', grade: 3, domain: Domain.first, course: Course.first}
seed Skill, {title: 'CCSS.MATH.CONTENT.3.OA.D.9', description: 'Identify arithmetic patterns (including patterns in the addition table or multiplication table), and explain them using properties of operations. For example, observe that 4 times a number is always even, and explain why 4 times a number can be decomposed into two equal addends.', grade: 3, domain: Domain.first, course: Course.first}
seed Skill, {title: 'CCSS.MATH.CONTENT.3.NBT.A.1', description: 'Use place value understanding to round whole numbers to the nearest 10 or 100.', grade: 3, domain: Domain.second, course: Course.first}
seed Skill, {title: 'CCSS.MATH.CONTENT.3.NBT.A.2', description: 'Fluently add and subtract within 1000 using strategies and algorithms based on place value, properties of operations, and/or the relationship between addition and subtraction.', grade: 3, domain: Domain.second, course: Course.first}
seed Skill, {title: 'CCSS.MATH.CONTENT.3.NBT.A.3', description: 'Multiply one-digit whole numbers by multiples of 10 in the range 10-90 (e.g., 9 × 80, 5 × 60) using strategies based on place value and properties of operations.', grade: 3, domain: Domain.second, course: Course.first}
seed Skill, {title: 'CCSS.MATH.CONTENT.3.NF.A.1', description: 'Understand a fraction 1/b as the quantity formed by 1 part when a whole is partitioned into b equal parts; understand a fraction a/b as the quantity formed by a parts of size 1/b.', grade: 3, domain: Domain.third, course: Course.first}
seed Skill, {title: 'CCSS.MATH.CONTENT.3.NF.A.2', description: 'Understand a fraction as a number on the number line; represent fractions on a number line diagram.', grade: 3, domain: Domain.third, course: Course.first}
seed Skill, {title: 'CCSS.MATH.CONTENT.3.NF.A.3', description: 'Explain equivalence of fractions in special cases, and compare fractions by reasoning about their size.', grade: 3, domain: Domain.third, course: Course.first}
seed Skill, {title: 'CCSS.MATH.CONTENT.3.MD.A.1', description: 'Tell and write time to the nearest minute and measure time intervals in minutes. Solve word problems involving addition and subtraction of time intervals in minutes, e.g., by representing the problem on a number line diagram.', grade: 3, domain: Domain.fourth, course: Course.first}
seed Skill, {title: 'CCSS.MATH.CONTENT.3.MD.A.2', description: 'Measure and estimate liquid volumes and masses of objects using standard units of grams (g), kilograms (kg), and liters (l). Add, subtract, multiply, or divide to solve one-step word problems involving masses or volumes that are given in the same units, e.g., by using drawings (such as a beaker with a measurement scale) to represent the problem.', grade: 3, domain: Domain.fourth, course: Course.first}
seed Skill, {title: 'CCSS.MATH.CONTENT.3.MD.B.3', description: 'Draw a scaled picture graph and a scaled bar graph to represent a data set with several categories. Solve one- and two-step "how many more" and "how many less" problems using information presented in scaled bar graphs. For example, draw a bar graph in which each square in the bar graph might represent 5 pets.', grade: 3, domain: Domain.fourth, course: Course.first}
seed Skill, {title: 'CCSS.MATH.CONTENT.3.MD.B.4', description: 'Generate measurement data by measuring lengths using rulers marked with halves and fourths of an inch. Show the data by making a line plot, where the horizontal scale is marked off in appropriate units— whole numbers, halves, or quarters.', grade: 3, domain: Domain.fourth, course: Course.first}
seed Skill, {title: 'CCSS.MATH.CONTENT.3.MD.C.5', description: 'Recognize area as an attribute of plane figures and understand concepts of area measurement.', grade: 3, domain: Domain.fourth, course: Course.first}
seed Skill, {title: 'CCSS.MATH.CONTENT.3.MD.C.6', description: 'Measure areas by counting unit squares (square cm, square m, square in, square ft, and improvised units).', grade: 3, domain: Domain.fourth, course: Course.first}
seed Skill, {title: 'CCSS.MATH.CONTENT.3.MD.C.7', description: 'Relate area to the operations of multiplication and addition.', grade: 3, domain: Domain.fourth, course: Course.first}
seed Skill, {title: 'CCSS.MATH.CONTENT.3.MD.C.8', description: 'Solve real world and mathematical problems involving perimeters of polygons, including finding the perimeter given the side lengths, finding an unknown side length, and exhibiting rectangles with the same perimeter and different areas or with the same area and different perimeters.', grade: 3, domain: Domain.fourth, course: Course.first}
seed Skill, {title: 'CCSS.MATH.CONTENT.3.G.A.1', description: 'Understand that shapes in different categories (e.g., rhombuses, rectangles, and others) may share attributes (e.g., having four sides), and that the shared attributes can define a larger category (e.g., quadrilaterals). Recognize rhombuses, rectangles, and squares as examples of quadrilaterals, and draw examples of quadrilaterals that do not belong to any of these subcategories.', grade: 3, domain: Domain.fifth, course: Course.first}
seed Skill, {title: 'CCSS.MATH.CONTENT.3.G.A.2', description: 'Partition shapes into parts with equal areas. Express the area of each part as a unit fraction of the whole. For example, partition a shape into 4 parts with equal area, and describe the area of each part as 1/4 of the area of the shape.', grade: 3, domain: Domain.fifth, course: Course.first}

seed Skill, {title: 'CCSS.MATH.CONTENT.4.OA.A.1', description: 'Interpret a multiplication equation as a comparison, e.g., interpret 35 = 5 × 7 as a statement that 35 is 5 times as many as 7 and 7 times as many as 5. Represent verbal statements of multiplicative comparisons as multiplication equations.', grade: 4, domain: Domain.first, course: Course.first}
seed Skill, {title: 'CCSS.MATH.CONTENT.4.OA.A.2', description: 'Multiply or divide to solve word problems involving multiplicative comparison, e.g., by using drawings and equations with a symbol for the unknown number to represent the problem, distinguishing multiplicative comparison from additive comparison.', grade: 4, domain: Domain.first, course: Course.first}
seed Skill, {title: 'CCSS.MATH.CONTENT.4.OA.A.3', description: 'Solve multistep word problems posed with whole numbers and having whole-number answers using the four operations, including problems in which remainders must be interpreted. Represent these problems using equations with a letter standing for the unknown quantity. Assess the reasonableness of answers using mental computation and estimation strategies including rounding.', grade: 4, domain: Domain.first, course: Course.first}
seed Skill, {title: 'CCSS.MATH.CONTENT.4.OA.B.4', description: 'Find all factor pairs for a whole number in the range 1-100. Recognize that a whole number is a multiple of each of its factors. Determine whether a given whole number in the range 1-100 is a multiple of a given one-digit number. Determine whether a given whole number in the range 1-100 is prime or composite.', grade: 4, domain: Domain.first, course: Course.first}
seed Skill, {title: 'CCSS.MATH.CONTENT.4.OA.C.5', description: 'Generate a number or shape pattern that follows a given rule. Identify apparent features of the pattern that were not explicit in the rule itself. For example, given the rule "Add 3" and the starting number 1, generate terms in the resulting sequence and observe that the terms appear to alternate between odd and even numbers. Explain informally why the numbers will continue to alternate in this way.', grade: 4, domain: Domain.first, course: Course.first}
seed Skill, {title: 'CCSS.MATH.CONTENT.4.NBT.A.1', description: 'Recognize that in a multi-digit whole number, a digit in one place represents ten times what it represents in the place to its right. For example, recognize that 700 ÷ 70 = 10 by applying concepts of place value and division.', grade: 4, domain: Domain.second, course: Course.first}
seed Skill, {title: 'CCSS.MATH.CONTENT.4.NBT.A.2', description: 'Read and write multi-digit whole numbers using base-ten numerals, number names, and expanded form. Compare two multi-digit numbers based on meanings of the digits in each place, using >, =, and < symbols to record the results of comparisons.', grade: 4, domain: Domain.second, course: Course.first}
seed Skill, {title: 'CCSS.MATH.CONTENT.4.NBT.A.3', description: 'Use place value understanding to round multi-digit whole numbers to any place.', grade: 4, domain: Domain.second, course: Course.first}
seed Skill, {title: 'CCSS.MATH.CONTENT.4.NBT.B.4', description: 'Fluently add and subtract multi-digit whole numbers using the standard algorithm.', grade: 4, domain: Domain.second, course: Course.first}
seed Skill, {title: 'CCSS.MATH.CONTENT.4.NBT.B.5', description: 'Multiply a whole number of up to four digits by a one-digit whole number, and multiply two two-digit numbers, using strategies based on place value and the properties of operations. Illustrate and explain the calculation by using equations, rectangular arrays, and/or area models.', grade: 4, domain: Domain.second, course: Course.first}
seed Skill, {title: 'CCSS.MATH.CONTENT.4.NBT.B.6', description: 'Find whole-number quotients and remainders with up to four-digit dividends and one-digit divisors, using strategies based on place value, the properties of operations, and/or the relationship between multiplication and division. Illustrate and explain the calculation by using equations, rectangular arrays, and/or area models.', grade: 4, domain: Domain.second, course: Course.first}
seed Skill, {title: 'CCSS.MATH.CONTENT.4.NF.A.1', description: 'fraction models, with attention to how the number and size of the parts differ even though the two fractions themselves are the same size. Use this principle to recognize and generate equivalent fractions.', grade: 4, domain: Domain.fifth, course: Course.first}
seed Skill, {title: 'CCSS.MATH.CONTENT.4.NF.A.2', description: 'Compare two fractions with different numerators and different denominators, e.g., by creating common denominators or numerators, or by comparing to a benchmark fraction such as 1/2. Recognize that comparisons are valid only when the two fractions refer to the same whole. Record the results of comparisons with symbols >, =, or <, and justify the conclusions, e.g., by using a visual fraction model.', grade: 4, domain: Domain.fifth, course: Course.first}
seed Skill, {title: 'CCSS.MATH.CONTENT.4.NF.B.3', description: 'Understand a fraction a/b with a > 1 as a sum of fractions 1/b.', grade: 4, domain: Domain.fifth, course: Course.first}
seed Skill, {title: 'CCSS.MATH.CONTENT.4.NF.B.4', description: 'Apply and extend previous understandings of multiplication to multiply a fraction by a whole number.', grade: 4, domain: Domain.fifth, course: Course.first}
seed Skill, {title: 'CCSS.MATH.CONTENT.4.NF.C.5', description: 'Express a fraction with denominator 10 as an equivalent fraction with denominator 100, and use this technique to add two fractions with respective denominators 10 and 100.2 For example, express 3/10 as 30/100, and add 3/10 + 4/100 = 34/100.', grade: 4, domain: Domain.fifth, course: Course.first}
seed Skill, {title: 'CCSS.MATH.CONTENT.4.NF.C.6', description: 'Use decimal notation for fractions with denominators 10 or 100. For example, rewrite 0.62 as 62/100; describe a length as 0.62 meters; locate 0.62 on a number line diagram.', grade: 4, domain: Domain.fifth, course: Course.first}
seed Skill, {title: 'CCSS.MATH.CONTENT.4.NF.C.7', description: 'Compare two decimals to hundredths by reasoning about their size. Recognize that comparisons are valid only when the two decimals refer to the same whole. Record the results of comparisons with the symbols >, =, or <, and justify the conclusions, e.g., by using a visual model.', grade: 4, domain: Domain.fifth, course: Course.first}
seed Skill, {title: 'CCSS.MATH.CONTENT.4.MD.A.1', description: 'Know relative sizes of measurement units within one system of units including km, m, cm; kg, g; lb, oz.; l, ml; hr, min, sec. Within a single system of measurement, express measurements in a larger unit in terms of a smaller unit. Record measurement equivalents in a two-column table. For example, know that 1 ft is 12 times as long as 1 in. Express the length of a 4 ft snake as 48 in. Generate a conversion table for feet and inches listing the number pairs (1, 12), (2, 24), (3, 36), ...', grade: 4, domain: Domain.third, course: Course.first}
seed Skill, {title: 'CCSS.MATH.CONTENT.4.MD.A.2', description: 'Use the four operations to solve word problems involving distances, intervals of time, liquid volumes, masses of objects, and money, including problems involving simple fractions or decimals, and problems that require expressing measurements given in a larger unit in terms of a smaller unit. Represent measurement quantities using diagrams such as number line diagrams that feature a measurement scale.', grade: 4, domain: Domain.third, course: Course.first}
seed Skill, {title: 'CCSS.MATH.CONTENT.4.MD.A.3', description: 'Apply the area and perimeter formulas for rectangles in real world and mathematical problems. For example, find the width of a rectangular room given the area of the flooring and the length, by viewing the area formula as a multiplication equation with an unknown factor.', grade: 4, domain: Domain.third, course: Course.first}
seed Skill, {title: 'CCSS.MATH.CONTENT.4.MD.B.4', description: 'Make a line plot to display a data set of measurements in fractions of a unit (1/2, 1/4, 1/8). Solve problems involving addition and subtraction of fractions by using information presented in line plots. For example, from a line plot find and interpret the difference in length between the longest and shortest specimens in an insect collection.', grade: 4, domain: Domain.third, course: Course.first}
seed Skill, {title: 'CCSS.MATH.CONTENT.4.MD.C.5', description: 'Recognize angles as geometric shapes that are formed wherever two rays share a common endpoint, and understand concepts of angle measurement:', grade: 4, domain: Domain.third, course: Course.first}
seed Skill, {title: 'CCSS.MATH.CONTENT.4.MD.C.6', description: 'Measure angles in whole-number degrees using a protractor. Sketch angles of specified measure.', grade: 4, domain: Domain.third, course: Course.first}
seed Skill, {title: 'CCSS.MATH.CONTENT.4.MD.C.7', description: 'Recognize angle measure as additive. When an angle is decomposed into non-overlapping parts, the angle measure of the whole is the sum of the angle measures of the parts. Solve addition and subtraction problems to find unknown angles on a diagram in real world and mathematical problems, e.g., by using an equation with a symbol for the unknown angle measure.', grade: 4, domain: Domain.third, course: Course.first}
seed Skill, {title: 'CCSS.MATH.CONTENT.4.G.A.1', description: 'Draw points, lines, line segments, rays, angles (right, acute, obtuse), and perpendicular and parallel lines. Identify these in two-dimensional figures.', grade: 4, domain: Domain.fourth, course: Course.first}
seed Skill, {title: 'CCSS.MATH.CONTENT.4.G.A.2', description: 'Classify two-dimensional figures based on the presence or absence of parallel or perpendicular lines, or the presence or absence of angles of a specified size. Recognize right triangles as a category, and identify right triangles.', grade: 4, domain: Domain.fourth, course: Course.first}
seed Skill, {title: 'CCSS.MATH.CONTENT.4.G.A.3', description: 'Recognize a line of symmetry for a two-dimensional figure as a line across the figure such that the figure can be folded along the line into matching parts. Identify line-symmetric figures and draw lines of symmetry.', grade: 4, domain: Domain.fourth, course: Course.first}

seed Skill, {title: 'CCSS.MATH.CONTENT.5.OA.A.1', description: 'Use parentheses, brackets, or braces in numerical expressions, and evaluate expressions with these symbols.', grade: 5, domain: Domain.first, course: Course.first}
seed Skill, {title: 'CCSS.MATH.CONTENT.5.OA.A.2', description: 'Write simple expressions that record calculations with numbers, and interpret numerical expressions without evaluating them. For example, express the calculation "add 8 and 7, then multiply by 2" as 2 × (8 + 7). Recognize that 3 × (18932 + 921) is three times as large as 18932 + 921, without having to calculate the indicated sum or product.', grade: 5, domain: Domain.first, course: Course.first}
seed Skill, {title: 'CCSS.MATH.CONTENT.5.OA.B.3', description: 'Generate two numerical patterns using two given rules. Identify apparent relationships between corresponding terms. Form ordered pairs consisting of corresponding terms from the two patterns, and graph the ordered pairs on a coordinate plane. For example, given the rule "Add 3" and the starting number 0, and given the rule "Add 6" and the starting number 0, generate terms in the resulting sequences, and observe that the terms in one sequence are twice the corresponding terms in the other sequence. Explain informally why this is so.', grade: 5, domain: Domain.first, course: Course.first}
seed Skill, {title: 'CCSS.MATH.CONTENT.5.NBT.A.1', description: 'Recognize that in a multi-digit number, a digit in one place represents 10 times as much as it represents in the place to its right and 1/10 of what it represents in the place to its left.', grade: 5, domain: Domain.second, course: Course.first}
seed Skill, {title: 'CCSS.MATH.CONTENT.5.NBT.A.2', description: 'Explain patterns in the number of zeros of the product when multiplying a number by powers of 10, and explain patterns in the placement of the decimal point when a decimal is multiplied or divided by a power of 10. Use whole-number exponents to denote powers of 10.', grade: 5, domain: Domain.second, course: Course.first}
seed Skill, {title: 'CCSS.MATH.CONTENT.5.NBT.A.3', description: 'Read, write, and compare decimals to thousandths.', grade: 5, domain: Domain.second, course: Course.first}
seed Skill, {title: 'CCSS.MATH.CONTENT.5.NBT.A.4', description: 'Use place value understanding to round decimals to any place.', grade: 5, domain: Domain.second, course: Course.first}
seed Skill, {title: 'CCSS.MATH.CONTENT.5.NBT.B.5', description: 'Fluently multiply multi-digit whole numbers using the standard algorithm.', grade: 5, domain: Domain.second, course: Course.first}
seed Skill, {title: 'CCSS.MATH.CONTENT.5.NBT.B.6', description: 'Find whole-number quotients of whole numbers with up to four-digit dividends and two-digit divisors, using strategies based on place value, the properties of operations, and/or the relationship between multiplication and division. Illustrate and explain the calculation by using equations, rectangular arrays, and/or area models.', grade: 5, domain: Domain.second, course: Course.first}
seed Skill, {title: 'CCSS.MATH.CONTENT.5.NBT.B.7', description: 'Add, subtract, multiply, and divide decimals to hundredths, using concrete models or drawings and strategies based on place value, properties of operations, and/or the relationship between addition and subtraction; relate the strategy to a written method and explain the reasoning used.', grade: 5, domain: Domain.second, course: Course.first}
seed Skill, {title: 'CCSS.MATH.CONTENT.5.NF.A.1', description: 'Add and subtract fractions with unlike denominators (including mixed numbers) by replacing given fractions with equivalent fractions in such a way as to produce an equivalent sum or difference of fractions with like denominators. For example, 2/3 + 5/4 = 8/12 + 15/12 = 23/12. (In general, a/b + c/d = (ad + bc)/bd.)', grade: 5, domain: Domain.fifth, course: Course.first}
seed Skill, {title: 'CCSS.MATH.CONTENT.5.NF.A.2', description: 'Solve word problems involving addition and subtraction of fractions referring to the same whole, including cases of unlike denominators, e.g., by using visual fraction models or equations to represent the problem. Use benchmark fractions and number sense of fractions to estimate mentally and assess the reasonableness of answers. For example, recognize an incorrect result 2/5 + 1/2 = 3/7, by observing that 3/7 < 1/2.', grade: 5, domain: Domain.fifth, course: Course.first}
seed Skill, {title: 'CCSS.MATH.CONTENT.5.NF.B.3', description: 'Interpret a fraction as division of the numerator by the denominator (a/b = a ÷ b). Solve word problems involving division of whole numbers leading to answers in the form of fractions or mixed numbers, e.g., by using visual fraction models or equations to represent the problem. For example, interpret 3/4 as the result of dividing 3 by 4, noting that 3/4 multiplied by 4 equals 3, and that when 3 wholes are shared equally among 4 people each person has a share of size 3/4. If 9 people want to share a 50-pound sack of rice equally by weight, how many pounds of rice should each person get? Between what two whole numbers does your answer lie?', grade: 5, domain: Domain.fifth, course: Course.first}
seed Skill, {title: 'CCSS.MATH.CONTENT.5.NF.B.4', description: 'Apply and extend previous understandings of multiplication to multiply a fraction or whole number by a fraction.', grade: 5, domain: Domain.fifth, course: Course.first}
seed Skill, {title: 'CCSS.MATH.CONTENT.5.NF.B.5', description: 'Interpret multiplication as scaling (resizing)', grade: 5, domain: Domain.fifth, course: Course.first}
seed Skill, {title: 'CCSS.MATH.CONTENT.5.NF.B.6', description: 'Solve real world problems involving multiplication of fractions and mixed numbers, e.g., by using visual fraction models or equations to represent the problem.', grade: 5, domain: Domain.fifth, course: Course.first}
seed Skill, {title: 'CCSS.MATH.CONTENT.5.NF.B.7', description: 'Apply and extend previous understandings of division to divide unit fractions by whole numbers and whole numbers by unit fractions.', grade: 5, domain: Domain.fifth, course: Course.first}
seed Skill, {title: 'CCSS.MATH.CONTENT.5.MD.A.1', description: 'Convert among different-sized standard measurement units within a given measurement system (e.g., convert 5 cm to 0.05 m), and use these conversions in solving multi-step, real world problems.', grade: 5, domain: Domain.third, course: Course.first}
seed Skill, {title: 'CCSS.MATH.CONTENT.5.MD.B.2', description: 'Make a line plot to display a data set of measurements in fractions of a unit (1/2, 1/4, 1/8). Use operations on fractions for this grade to solve problems involving information presented in line plots. For example, given different measurements of liquid in identical beakers, find the amount of liquid each beaker would contain if the total amount in all the beakers were redistributed equally.', grade: 5, domain: Domain.third, course: Course.first}
seed Skill, {title: 'CCSS.MATH.CONTENT.5.MD.C.3', description: 'Recognize volume as an attribute of solid figures and understand concepts of volume measurement.', grade: 5, domain: Domain.third, course: Course.first}
seed Skill, {title: 'CCSS.MATH.CONTENT.5.MD.C.4', description: 'Measure volumes by counting unit cubes, using cubic cm, cubic in, cubic ft, and improvised units.', grade: 5, domain: Domain.third, course: Course.first}
seed Skill, {title: 'CCSS.MATH.CONTENT.5.MD.C.5', description: 'Relate volume to the operations of multiplication and addition and solve real world and mathematical problems involving volume.', grade: 5, domain: Domain.third, course: Course.first}
seed Skill, {title: 'CCSS.MATH.CONTENT.5.G.A.1', description: 'Use a pair of perpendicular number lines, called axes, to define a coordinate system, with the intersection of the lines (the origin) arranged to coincide with the 0 on each line and a given point in the plane located by using an ordered pair of numbers, called its coordinates. Understand that the first number indicates how far to travel from the origin in the direction of one axis, and the second number indicates how far to travel in the direction of the second axis, with the convention that the names of the two axes and the coordinates correspond (e.g., x-axis and x-coordinate, y-axis and y-coordinate).', grade: 5, domain: Domain.fourth, course: Course.first}
seed Skill, {title: 'CCSS.MATH.CONTENT.5.G.A.2', description: 'Represent real world and mathematical problems by graphing points in the first quadrant of the coordinate plane, and interpret coordinate values of points in the context of the situation.', grade: 5, domain: Domain.fourth, course: Course.first}
seed Skill, {title: 'CCSS.MATH.CONTENT.5.G.B.3', description: 'Understand that attributes belonging to a category of two-dimensional figures also belong to all subcategories of that category. For example, all rectangles have four right angles and squares are rectangles, so all squares have four right angles.', grade: 5, domain: Domain.fourth, course: Course.first}
seed Skill, {title: 'CCSS.MATH.CONTENT.5.G.B.4', description: 'Classify two-dimensional figures in a hierarchy based on properties.', grade: 5, domain: Domain.fourth, course: Course.first}

game1 = seed Game, {title: 'Maths Man'}, {redirect_uri: 'urn:ietf:wg:oauth:2.0:oob'}
seed GameSkill, {game_id: game1.id, skill_id: skill1.id}

game2 = seed Game, {title: 'Maths Man 2'}, {redirect_uri: 'urn:ietf:wg:oauth:2.0:oob'}
seed GameSkill, {game_id: game2.id, skill_id: skill1.id}

game3 = seed Game, {title: 'Build a tower'}, {redirect_uri: 'urn:ietf:wg:oauth:2.0:oob'}
seed GameSkill, {game_id: game3.id, skill_id: skill2.id}

game4 = seed Game, {title: 'Build a tower 2'}, {redirect_uri: 'urn:ietf:wg:oauth:2.0:oob'}
seed GameSkill, {game_id: game4.id, skill_id: skill2.id}

seed CompletedStudentSkill, {student_id: student1.id, skill_id: skill1.id, collected: false}
seed CompletedStudentSkill, {student_id: student1.id, skill_id: skill2.id, collected: true}
seed CompletedStudentSkill, {student_id: student2.id, skill_id: skill2.id, collected: true}
